AWSTemplateFormatVersion: '2010-09-09'

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sam-scratch-graphql

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref Bucket
                - /*
